CREATE TABLE `load_quotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`vanLat` decimal(10,7) NOT NULL,
	`vanLng` decimal(10,7) NOT NULL,
	`vanAddress` text NOT NULL,
	`pickupLat` decimal(10,7) NOT NULL,
	`pickupLng` decimal(10,7) NOT NULL,
	`pickupAddress` text NOT NULL,
	`deliveryLat` decimal(10,7) NOT NULL,
	`deliveryLng` decimal(10,7) NOT NULL,
	`deliveryAddress` text NOT NULL,
	`weight` decimal(10,2) NOT NULL,
	`weightUnit` varchar(10) NOT NULL DEFAULT 'lbs',
	`cargoDescription` text,
	`emptyMiles` decimal(10,2) NOT NULL,
	`loadedMiles` decimal(10,2) NOT NULL,
	`returnEmptyMiles` decimal(10,2) DEFAULT '0',
	`totalMiles` decimal(10,2) NOT NULL,
	`ratePerMile` decimal(10,2) NOT NULL,
	`ratePerPound` decimal(10,4) DEFAULT '0',
	`fuelSurcharge` decimal(10,2) DEFAULT '0',
	`totalPrice` decimal(10,2) NOT NULL,
	`estimatedFuelCost` decimal(10,2) DEFAULT '0',
	`estimatedOperatingCost` decimal(10,2) DEFAULT '0',
	`estimatedProfit` decimal(10,2) DEFAULT '0',
	`profitMarginPercent` decimal(5,2) DEFAULT '0',
	`status` enum('draft','quoted','accepted','rejected','expired') NOT NULL DEFAULT 'draft',
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `load_quotations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `load_quotations` ADD CONSTRAINT `load_quotations_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;