CREATE TABLE `quote_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`loadId` int NOT NULL,
	`brokerId` int,
	`brokerName` varchar(255),
	`routeName` varchar(255),
	`totalMiles` decimal(10,2) NOT NULL,
	`loadedMiles` decimal(10,2) NOT NULL,
	`emptyMiles` decimal(10,2) DEFAULT '0.00',
	`baseRate` decimal(12,2) NOT NULL,
	`distanceSurcharge` decimal(12,2) DEFAULT '0.00',
	`weightSurcharge` decimal(12,2) DEFAULT '0.00',
	`otherSurcharges` decimal(12,2) DEFAULT '0.00',
	`totalIncome` decimal(12,2) NOT NULL,
	`estimatedFuel` decimal(12,2) NOT NULL,
	`estimatedTolls` decimal(12,2) DEFAULT '0.00',
	`estimatedMaintenance` decimal(12,2) DEFAULT '0.00',
	`estimatedInsurance` decimal(12,2) DEFAULT '0.00',
	`estimatedOther` decimal(12,2) DEFAULT '0.00',
	`totalEstimatedCost` decimal(12,2) NOT NULL,
	`estimatedProfit` decimal(12,2) NOT NULL,
	`estimatedMargin` decimal(5,2) NOT NULL,
	`ratePerLoadedMile` decimal(10,2) NOT NULL,
	`recommendedMinimumRate` decimal(10,2) NOT NULL,
	`rateVsMinimum` decimal(10,2) NOT NULL,
	`verdict` enum('accept','negotiate','reject') NOT NULL,
	`decisionReason` text,
	`actualFuel` decimal(12,2),
	`actualTolls` decimal(12,2),
	`actualMaintenance` decimal(12,2),
	`actualInsurance` decimal(12,2),
	`actualOther` decimal(12,2),
	`totalActualCost` decimal(12,2),
	`actualProfit` decimal(12,2),
	`actualMargin` decimal(5,2),
	`costVariance` decimal(12,2),
	`profitVariance` decimal(12,2),
	`marginVariance` decimal(5,2),
	`analyzedBy` int NOT NULL,
	`analyzedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quote_analysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `quote_analysis` ADD CONSTRAINT `quote_analysis_loadId_loads_id_fk` FOREIGN KEY (`loadId`) REFERENCES `loads`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `quote_analysis` ADD CONSTRAINT `quote_analysis_brokerId_users_id_fk` FOREIGN KEY (`brokerId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `quote_analysis` ADD CONSTRAINT `quote_analysis_analyzedBy_users_id_fk` FOREIGN KEY (`analyzedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;